services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: <your_username>
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: todo-app
      PGDATA: /data/postgres
    volumes:
      - ./schema/init.up.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres:/data/postgres
    ports:
      - "5442:5432"
